### ISSUE TITLE
[feature] Add support for Monero Custom Server (Add LightWallet API Support)

### ISSUE THREAD

**Issue by CryptoGrampy** [EdgeApp/edge-currency-monero#80]
I'm not sure this is the best repo to add this feature request, but I would like to see support added to EdgeWallet for allowing users to specify and use a custom Monero Light Wallet server that follows the Monero LightWallet API: https://github.com/monero-project/meta/blob/master/api/lightwallet_rest.md
Self-Hosted Monero-LWS implementation: https://github.com/vtnerd/monero-lws/

Edge is currently the only wallet suggested on getmonero that doesn't offer users a way to use their own server. Wallets like Cake allow users to specify their own nodes, and MyMonero allows users to use their own light wallet servers.  

I will be increasingly advocating for the removal of any wallets that don't allow this feature from the getmonero.org download section as well as any other communities- Reddit, Twitter etc where they are suggested.  

Reference: 
https://github.com/monero-project/monero-site/issues/2162
https://www.reddit.com/r/Monero/comments/136z96p/proposal_remove_light_wallets_from_sidebar_and/

Currently the only option in Edge is to use the MyMonero proprietary server; using centralized services is not only dangerous for user privacy, it's actually destructive to the system privacy that Monero users pay for.

**Comment by swansontec** [comment]
Thanks. Edge has wanted this capability for a while, but we haven't had the resources to implement it. This API does look pretty straightforward, so adding support looks like a reasonably-sized undertaking. I will bring it up at our project-planning meeting and see if we can get it scheduled for an upcoming sprint.

**Comment by swansontec** [comment]
We have asked @itayplav to work on this feature.

**Comment by robster7674** [comment]
In https://odysee.com/@MoneroTalk:8/p2p-betting-using-sigmanero-price,-news:d, 12:15 onwards the host talks about Edge using LightWallet now. Is that correct?

**Comment by paullinator** [comment]
@robster7674 we still use MyMonero but we now allow a custom LWS server to be used. That feature has been live for months

**Comment by paullinator** [comment]
Closing as resolved
